

>>> #   Arrays




In [ ]:
import numpy as np
a = np.array([1,3,5,7])
b = np.array([2,4,6,8])

In [ ]:
a.shape

(4,)

In [ ]:
a.ndim

1

## Norm
$||a|| = \sqrt{\sum_{d=1}^Da_d^2}$ 

In [ ]:
np.linalg.norm(a)

9.16515138991168

## Sum

$a+b = \sum_{d = 1}^D a_d + b_d$

In [ ]:
a + b

array([ 3,  7, 11, 15])



## Dot Product
$a \cdot b = a^Tb = \sum_{d=1}^D a_db_d $

$a \cdot b = ||{a}||\; ||b||\;cos\theta$

In [ ]:
a @ b

100

In [ ]:
a.dot(b)

100

##Element-Wise Operations

In [ ]:
2 * a

array([ 2,  6, 10, 14])

In [ ]:
np.exp(a)

array([   2.71828183,   20.08553692,  148.4131591 , 1096.63315843])

In [ ]:
2.5 + a

array([3.5, 5.5, 7.5, 9.5])

>>> # Miscellaneous

## Generating Data

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,2)) * 7

array([[7., 7.],
       [7., 7.],
       [7., 7.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random

In [ ]:
np.random.rand() # Uniform Distribution

0.9803951750451535

In [ ]:
np.random.rand(3,2)

array([[0.9382362 , 0.21501134],
       [0.90293724, 0.29206137],
       [0.20741596, 0.77980032]])

In [ ]:
np.random.randn() # Standard Normal Distribution

-1.4675738732930441

In [ ]:
np.random.randn(2,3)

array([[-0.9032918 ,  0.64783509,  0.58857644],
       [-1.88848489,  0.30180312, -0.50844459]])

In [ ]:
R = np.random.randint(1,101,size = 1000) # Discrete uniform distribution

In [ ]:
R.mean()

50.008

In [ ]:
np.random.choice(R,size = 3, replace = False) 

array([84, 99, 91])

## Statistical Methods

In [ ]:
A = np.random.randn(10000) #  Array

In [ ]:
A.mean()

-0.002291456271984444

In [ ]:
A.var()

0.9995527223058854

In [ ]:
A.std()

0.9997763361401816

In [ ]:
M = np.random.randn(1000,3) # Matrix

In [ ]:
M.mean(axis = 0) # Mean of each column

array([-0.01270171, -0.04153376, -0.00119593])

In [ ]:
M.mean(axis = 1).shape

(1000,)


Suppose M is a data sets (1000 samples, 3 attributes)

Covariance for each attribute


In [ ]:
# Transpose because the function treats each columns as a sample, not each row
np.cov(M.T) 

array([[ 0.9588717 , -0.05132158,  0.00245986],
       [-0.05132158,  1.01200779,  0.05290432],
       [ 0.00245986,  0.05290432,  0.99593089]])

>>> # Matrices

In [ ]:
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
d = np.random.randn(4,3) * 5

In [ ]:
d

array([[ 4.26734593,  4.32356007, -6.25881874],
       [-1.71474903,  3.8850364 , -6.58154203],
       [ 2.78340119,  1.81872673, -1.86173697],
       [ 3.73602096,  3.03136485, -4.63813832]])

In [ ]:
c.shape

(4, 3)

In [ ]:
c.ndim

2

## Diagonals

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.diag([1,3,5])

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [ ]:
np.diag(c)

array([1, 5, 9])

## Sum


In [ ]:
c + d

array([[ 5.26734593,  6.32356007, -3.25881874],
       [ 2.28525097,  8.8850364 , -0.58154203],
       [ 9.78340119,  9.81872673,  7.13826303],
       [13.73602096, 14.03136485,  7.36186168]])

## Multiplication

In [ ]:
e = np.random.randn(3,5)

In [ ]:
(d.shape , e.shape)

((4, 3), (3, 5))

In [ ]:
d.dot(e)

array([[-0.28779918,  1.11513742, 10.52961157,  1.81393322,  5.69884984],
       [-4.51074529,  5.61522731, 18.27115421, -4.44284202,  1.98533421],
       [ 0.89898792, -0.83180445,  1.99270551,  2.13031917,  2.58702099],
       [ 0.20284202,  0.46522124,  6.74795545,  1.90607518,  4.64827347]])

## Determinant

In [ ]:
f = np.random.randn(3,3)
f

array([[ 0.23565229,  0.68348704, -0.69165424],
       [-1.65671484, -1.75026948, -0.86280585],
       [-0.17202157,  1.28588378, -0.20149748]])

In [ ]:
np.linalg.det(f)

1.8995437039289247

## Inverse

In [ ]:
f_inv = np.linalg.inv(f)

In [ ]:
f_inv.dot(f)

array([[ 1.00000000e+00, -1.90965117e-17, -6.78130606e-18],
       [-5.14050704e-18,  1.00000000e+00, -1.25965636e-17],
       [ 3.14113962e-18,  1.42206128e-17,  1.00000000e+00]])

## Matrix trace
In linear algebra, the trace of a square matrix A, denoted tr(A), is defined to be the sum of elements on the main diagonal (from the upper left to the lower right) of A

In [ ]:
np.trace(f)

-1.7161146711757764

## Eigenvalues and eigenvectors

np.ligalg.eig returns the (eigenvalues & eigenvectors) The eigenvectors are returned via columns

In [ ]:
g = np.random.randint(0,10,size=(3,3))
Lam,V = np.linalg.eig(g)

In [ ]:
V

array([[-0.47514597+0.j        , -0.43063942-0.44259876j,
        -0.43063942+0.44259876j],
       [-0.70487846+0.j        ,  0.63353764+0.j        ,
         0.63353764-0.j        ],
       [-0.52667131+0.j        , -0.24380183+0.39729933j,
        -0.24380183-0.39729933j]])

In [ ]:
V[:,0] * Lam[0]

array([ -8.28806519+0.j, -12.29533432+0.j,  -9.18683181+0.j])

In [ ]:
g @ V[:,0]

array([ -8.28806519+0.j, -12.29533432+0.j,  -9.18683181+0.j])

## Solving Linear Equation

In [ ]:
# Ax = b
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])
x = np.linalg.solve(A,b)
x

array([1500.,  700.])